#!/usr/bin/env bash
# Publish the Move package to Sui testnet.
# Usage: bash scripts/publish-testnet.sh
#
# Requires `sui` CLI configured for the testnet alias and an
# active address with testnet SUI
# (faucet: https://docs.sui.io/guides/developer/sui-101/get-testnet-sui).
#
# The script captures the published package id and writes it to
# <repo>/.env.testnet (SUI_PACKAGE_ID=...) so the Next.js dev server
# can pick it up via `set -a; . .env.testnet; set +a`.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
MOVE_DIR="$REPO_ROOT/move"
OUT="$REPO_ROOT/.env.testnet"

cd "$MOVE_DIR"
echo "Building..."
sui move build
echo
echo "Publishing to testnet..."
JSON=$(sui client publish --gas-budget 300000000 --json)
PKG=$(printf '%s' "$JSON" | python3 -c '
import json, sys
d = json.load(sys.stdin)
for c in d.get("objectChanges", []):
    if c.get("type") == "published":
        print(c["packageId"])
        break
')
if [ -z "$PKG" ]; then
  echo "ERROR: could not parse packageId from publish output:" >&2
  printf '%s\n' "$JSON" | head -40 >&2
  exit 1
fi
echo "Published package id: $PKG"
{
  echo "# generated by scripts/publish-testnet.sh at $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "SUI_PACKAGE_ID=$PKG"
  echo "SUI_GAS_BUDGET=50000000"
  echo "WALRUS_PUBLISHER_URL=https://publisher.walrus-testnet.walrus.space"
  echo "WALRUS_AGGREGATOR_URL=https://aggregator.walrus-testnet.walrus.space"
  echo "WALRUS_EPOCHS=1"
  echo "SUI_CLIENT_LIVE=1"
} > "$OUT"
echo "Wrote $OUT"
