#!/usr/bin/env bash
# Publish the Move package to Sui testnet.
# Usage: bash scripts/publish-testnet.sh
#
# Requires `sui` CLI configured for the testnet alias and an
# active address with testnet SUI (faucet: https://docs.sui.io/guides/developer/sui-101/get-testnet-sui).
#
# The script captures the published package id and writes it to
# ../.env.testnet (SUI_PACKAGE_ID=...) so the Next.js dev server
# can pick it up via `set -a; . .env.testnet; set +a`.
set -euo pipefail

cd "$(dirname "$0")/../move"
echo "Building..."
sui move build --skip-fetch-latest-git-deps
echo
echo "Publishing to testnet..."
JSON=$(sui client publish --gas-budget 500000000 --json --skip-fetch-latest-git-deps)
PKG=$(printf '%s' "$JSON" | python3 -c 'import json,sys; d=json.load(sys.stdin); print(d["objectChanges"][[c["type"] for c in d["objectChanges"]].index("published")]["packageId"])')
echo "Published package id: $PKG"
OUT="$(dirname "$0")/../.env.testnet"
{
  echo "# generated by scripts/publish-testnet.sh"
  echo "SUI_PACKAGE_ID=$PKG"
  echo "SUI_GAS_BUDGET=50000000"
  echo "WALRUS_PUBLISHER_URL=https://publisher.walrus-testnet.walrus.space"
  echo "WALRUS_AGGREGATOR_URL=https://aggregator.walrus-testnet.walrus.space"
  echo "SUI_CLIENT_LIVE=1"
} > "$OUT"
echo "Wrote $OUT"
